export const SCREEN_HERO_HEIGHT = 340;
export const SCREEN_HERO_CONTENT_BOTTOM = 34;
export const SCREEN_HERO_TOP_GRADIENT_HEIGHT = 120;
export const SCREEN_HERO_BOTTOM_GRADIENT_HEIGHT = 200;
export const SCREEN_HERO_HORIZONTAL_PADDING = 14;
