import {StyleSheet} from "react-native";

import {themeColors} from "@/utils/theme-colors";
import {
    SCREEN_HERO_BOTTOM_GRADIENT_HEIGHT,
    SCREEN_HERO_CONTENT_BOTTOM,
    SCREEN_HERO_HORIZONTAL_PADDING,
    SCREEN_HERO_SUBTITLE_FONT_SIZE,
    SCREEN_HERO_SUBTITLE_LINE_HEIGHT,
    SCREEN_HERO_TITLE_FONT_SIZE,
    SCREEN_HERO_TITLE_LINE_HEIGHT,
    SCREEN_HERO_TOP_GRADIENT_HEIGHT,
} from "@/features/screens/shared/hero-layout";

import {HERO_HEIGHT} from "./booking.constants";

const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: themeColors.background,
    },
    scroll: {
        flex: 1,
        backgroundColor: themeColors.background,
    },
    hero: {
        height: HERO_HEIGHT,
        position: "relative",
        backgroundColor: themeColors.background,
    },
    heroImageLayer: {
        ...StyleSheet.absoluteFillObject,
    },
    heroImage: {
        ...StyleSheet.absoluteFillObject,
    },
    heroOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.42)",
    },
    heroTopGradient: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: SCREEN_HERO_TOP_GRADIENT_HEIGHT,
    },
    heroBottomGradient: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        height: SCREEN_HERO_BOTTOM_GRADIENT_HEIGHT + 76,
    },
    heroContent: {
        position: "absolute",
        left: SCREEN_HERO_HORIZONTAL_PADDING,
        right: SCREEN_HERO_HORIZONTAL_PADDING,
        bottom: SCREEN_HERO_CONTENT_BOTTOM + 28,
        paddingBottom: 0,
    },
    heroPill: {
        alignSelf: "flex-start",
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
        paddingHorizontal: 11,
        paddingVertical: 7,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.18)",
        backgroundColor: "rgba(7,8,8,0.62)",
    },
    heroPillText: {
        color: themeColors.text,
        fontSize: 12,
        fontFamily: "Point-SemiBold",
    },
    heroTitle: {
        marginTop: 8,
        color: themeColors.primary,
        fontSize: SCREEN_HERO_TITLE_FONT_SIZE,
        lineHeight: SCREEN_HERO_TITLE_LINE_HEIGHT,
        fontFamily: "Point-Black",
    },
    heroSubtitle: {
        marginTop: 6,
        maxWidth: 360,
        color: themeColors.text,
        fontSize: SCREEN_HERO_SUBTITLE_FONT_SIZE,
        lineHeight: SCREEN_HERO_SUBTITLE_LINE_HEIGHT,
        fontFamily: "Point-Regular",
    },

    stickyFiltersWrapper: {
        zIndex: 20,
        backgroundColor: themeColors.background,
    },
    content: {
        paddingHorizontal: 12,
        backgroundColor: themeColors.background,
    },
    filtersRow: {
        flexDirection: "row",
        gap: 8,
        paddingTop: 0,
        paddingBottom: 14,
    },
    filterButton: {
        flexGrow: 1,
        flexShrink: 1,
        minWidth: 0,
        minHeight: 44,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 9,
        paddingVertical: 7,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
        backgroundColor: "rgba(18,18,16,0.96)",
    },
    filterButtonCompact: {
        flexGrow: 0,
        width: 48,
        paddingHorizontal: 6,
        justifyContent: "center",
    },
    filterIconWrap: {
        width: 28,
        height: 28,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    filterTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    filterLabel: {
        color: themeColors.textSecondary,
        fontSize: 11,
        lineHeight: 14,
        fontFamily: "Point-Regular",
    },
    filterValue: {
        marginTop: 2,
        color: themeColors.text,
        fontSize: 13,
        lineHeight: 16,
        fontFamily: "Point-SemiBold",
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 2,
        marginTop: 4,
        marginBottom: 12,
    },
    sectionTitle: {
        color: themeColors.text,
        fontSize: 20,
        lineHeight: 24,
        fontFamily: "Point-Bold",
    },
    sectionCount: {
        minWidth: 28,
        height: 28,
        borderRadius: 8,
        overflow: "hidden",
        textAlign: "center",
        textAlignVertical: "center",
        color: themeColors.textOnPrimary,
        fontSize: 13,
        lineHeight: 28,
        fontFamily: "Point-Bold",
        backgroundColor: themeColors.primary,
    },
    cardsList: {
        gap: 12,
    },
    bookingState: {
        minHeight: 120,
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        paddingHorizontal: 18,
        paddingVertical: 24,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
        backgroundColor: themeColors.card,
    },
    bookingStateText: {
        color: themeColors.textSecondary,
        fontSize: 14,
        lineHeight: 20,
        textAlign: "center",
        fontFamily: "Point-Regular",
    },
    bookingCard: {
        height: 196,
        overflow: "hidden",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.07)",
        backgroundColor: "#0f0f0d",
    },
    cardImage: {
        ...StyleSheet.absoluteFillObject,
    },
    cardImagePlaceholder: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: themeColors.cardSecondary,
    },
    cardGradient: {
        ...StyleSheet.absoluteFillObject,
    },
    cardContent: {
        flex: 1,
        justifyContent: "space-between",
        padding: 11,
    },
    cardTopRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    cardPill: {
        minWidth: 0,
        minHeight: 26,
        justifyContent: "center",
        paddingHorizontal: 8,
        borderRadius: 7,
        borderWidth: 1,
        borderColor: "rgba(236,172,24,0.32)",
        backgroundColor: "rgba(7,8,8,0.64)",
    },
    cardPillText: {
        color: themeColors.primary,
        fontSize: 11,
        lineHeight: 14,
        fontFamily: "Point-SemiBold",
    },
    cardPillMuted: {
        alignSelf: "flex-start",
        minHeight: 26,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 8,
        borderRadius: 7,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.10)",
        backgroundColor: "rgba(7,8,8,0.64)",
    },
    cardPillMutedText: {
        color: themeColors.text,
        fontSize: 11,
        lineHeight: 14,
        fontFamily: "Point-SemiBold",
    },
    cardTitle: {
        marginTop: "auto",
        color: themeColors.text,
        fontSize: 20,
        lineHeight: 24,
        fontFamily: "Point-Bold",
    },
    cardDescription: {
        marginTop: 6,
        color: "rgba(255,255,255,0.72)",
        fontSize: 13,
        lineHeight: 18,
        fontFamily: "Point-Regular",
    },
    cardFooter: {
        marginTop: 11,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    cardFooterText: {
        color: themeColors.primary,
        fontSize: 13,
        lineHeight: 16,
        fontFamily: "Point-Bold",
    },
    detailsBackground: {
        backgroundColor: themeColors.background,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
    },
    detailsHandle: {
        width: 42,
        height: 4,
        borderRadius: 999,
        backgroundColor: "rgba(255,255,255,0.22)",
    },
    detailsContent: {
        backgroundColor: themeColors.background,
    },
    gallery: {
        width: "100%",
        overflow: "hidden",
        backgroundColor: "#11110f",
    },
    galleryImage: {
        height: "100%",
    },
    galleryPlaceholder: {
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: themeColors.cardSecondary,
    },
    galleryCounter: {
        position: "absolute",
        right: 14,
        bottom: 14,
        minWidth: 48,
        minHeight: 28,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
        borderRadius: 7,
        backgroundColor: "rgba(7,8,8,0.72)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.12)",
    },
    galleryCounterText: {
        color: themeColors.text,
        fontSize: 12,
        lineHeight: 15,
        fontFamily: "Point-SemiBold",
    },
    detailsBody: {
        paddingHorizontal: 14,
        paddingTop: 18,
    },
    detailsMetaRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    detailsMetaPill: {
        minHeight: 32,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
        backgroundColor: themeColors.card,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
    },
    detailsMetaText: {
        color: themeColors.text,
        fontSize: 12,
        lineHeight: 15,
        fontFamily: "Point-SemiBold",
    },
    detailsTitle: {
        marginTop: 18,
        color: themeColors.text,
        fontSize: 24,
        lineHeight: 29,
        fontFamily: "Point-Bold",
    },
    detailsDescription: {
        marginTop: 12,
        color: themeColors.textSecondary,
        fontSize: 14,
        lineHeight: 21,
        fontFamily: "Point-Regular",
    },
    infoBlock: {
        marginTop: 20,
        overflow: "hidden",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
        backgroundColor: themeColors.card,
    },
    infoRow: {
        minHeight: 64,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: themeColors.cardBorder,
    },
    infoIcon: {
        width: 36,
        height: 36,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(236,172,24,0.10)",
    },
    infoTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    infoLabel: {
        color: themeColors.textSecondary,
        fontSize: 12,
        lineHeight: 15,
        fontFamily: "Point-Regular",
    },
    infoValue: {
        marginTop: 2,
        color: themeColors.text,
        fontSize: 14,
        lineHeight: 18,
        fontFamily: "Point-SemiBold",
    },
    detailsFooter: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingTop: 12,
        paddingHorizontal: 14,
        backgroundColor: themeColors.background,
        borderTopWidth: 1,
        borderTopColor: "rgba(255,255,255,0.08)",
    },
    reserveButton: {
        flex: 1.15,
        height: 48,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        backgroundColor: themeColors.primary,
    },
    reserveButtonText: {
        color: themeColors.textOnPrimary,
        fontSize: 14,
        lineHeight: 17,
        fontFamily: "Point-Bold",
    },
    whatsappButton: {
        flex: 0.85,
        height: 48,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 7,
        paddingHorizontal: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.10)",
        backgroundColor: "#1f7a45",
    },
    whatsappButtonText: {
        color: themeColors.text,
        fontSize: 14,
        lineHeight: 17,
        fontFamily: "Point-Bold",
    },
});

export default styles;
