import {StyleSheet} from "react-native";
import {SHADOW, themeColors} from "@/utils/theme-colors";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: themeColors.background,
    },
    header: {
        paddingTop: 16,
        paddingHorizontal: 16,
        alignItems: "center",
    },
    segment: {
        flexDirection: "row",
        width: "100%",
        maxWidth: 300,
        padding: 3,
        borderRadius: 12,
        backgroundColor: themeColors.card,
    },
    segmentButton: {
        flex: 1,
        height: 36,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    segmentButtonActive: {
        backgroundColor: themeColors.primary,
        ...SHADOW,
    },
    segmentText: {
        fontSize: 15,
        fontFamily: "Point-SemiBold",
        color: themeColors.textSecondary,
    },
    segmentTextActive: {
        color: themeColors.textOnPrimary,
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 20,
        gap: 16,
    },
    topText: {
        gap: 4,
    },
    title: {
        color: themeColors.text,
        fontSize: 20,
        fontFamily: "Point-Bold",
        letterSpacing: -0.4,
    },
    subtitle: {
        color: themeColors.textSecondary,
        fontSize: 14,
        fontFamily: "Point-Regular",
    },
    list: {
        flex: 1,
    },
    card: {
        minHeight: 58,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
        backgroundColor: themeColors.card,
        paddingHorizontal: 16,
        paddingVertical: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        marginBottom: 12,
    },
    cardSelected: {
        borderColor: themeColors.primary,
        backgroundColor: themeColors.cardHover,
    },
    cardRow: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        minWidth: 0,
    },
    cardText: {
        flex: 1,
        minWidth: 0,
        color: themeColors.text,
        fontSize: 16,
        fontFamily: "Point-SemiBold",
    },
    radio: {
        width: 22,
        height: 22,
        borderRadius: 11,
        borderWidth: 2,
        borderColor: themeColors.border,
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    radioSelected: {
        borderColor: themeColors.primary,
    },
    radioInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: themeColors.primary,
    },
    iconButton: {
        width: 34,
        height: 34,
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    restaurantCard: {
        borderRadius: 18,
        borderWidth: 1,
        borderColor: themeColors.border,
        backgroundColor: themeColors.card,
        padding: 10,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 12,
        marginBottom: 12,
    },
    restaurantCardSelected: {
        borderColor: themeColors.primary,
        backgroundColor: themeColors.background,
        ...SHADOW,
    },
    restaurantCardDisabled: {
        opacity: 0.52,
    },
    pressed: {
        opacity: 0.94,
    },
    restaurantImageWrap: {
        width: 92,
        height: 92,
        borderRadius: 16,
        overflow: "hidden",
        backgroundColor: themeColors.cardSecondary,
        flexShrink: 0,
    },
    restaurantImage: {
        width: "100%",
        height: "100%",
    },
    restaurantContent: {
        flex: 1,
        minWidth: 0,
        gap: 6,
        paddingTop: 2,
    },
    restaurantHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 10,
    },
    restaurantTitle: {
        flex: 1,
        minWidth: 0,
        color: themeColors.text,
        fontSize: 14,
        fontFamily: "Point-Bold",
        letterSpacing: 0.8,
    },
    restaurantAddress: {
        color: themeColors.textSecondary,
        fontSize: 12,
        fontFamily: "Point-Regular",
    },
    restaurantHours: {
        color: themeColors.textSecondary,
        fontSize: 12,
        fontFamily: "Point-Regular",
    },
    bottomPanel: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 16,
        backgroundColor: themeColors.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderTopWidth: 1,
        borderColor: themeColors.cardBorder,
        ...SHADOW,
    },
    panel: {
        gap: 14,
    },
    panelTitle: {
        color: themeColors.text,
        fontSize: 14,
        fontFamily: "Point-Bold",
        letterSpacing: 0.8,
    },
    modeList: {
        gap: 12,
    },
    modeRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    modeTextWrap: {
        flex: 1,
        minWidth: 0,
        gap: 2,
    },
    modeLabel: {
        color: themeColors.text,
        fontSize: 14,
        fontFamily: "Point-Bold",
        letterSpacing: 0.8,
    },
    modeLabelActive: {
        color: themeColors.primary,
    },
    modeValue: {
        color: themeColors.primary,
        fontSize: 14,
        fontFamily: "Point-SemiBold",
    },
    modeAction: {
        color: themeColors.notification,
        fontSize: 14,
        fontFamily: "Point-SemiBold",
        flexShrink: 0,
    },
    modeActionHidden: {
        opacity: 0,
    },
    sourceBlock: {
        gap: 2,
    },
    sourceLabel: {
        color: themeColors.textSecondary,
        fontSize: 12,
        fontFamily: "Point-Regular",
    },
    sourceTitle: {
        color: themeColors.text,
        fontSize: 14,
        fontFamily: "Point-Bold",
        letterSpacing: 0.8,
    },
    primaryButton: {
        minHeight: 54,
        borderRadius: 12,
        backgroundColor: themeColors.primary,
        paddingHorizontal: 16,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    primaryButtonDisabled: {
        opacity: 0.55,
    },
    primaryButtonText: {
        color: themeColors.textOnPrimary,
        fontSize: 16,
        fontFamily: "Point-SemiBold",
    },
    panelWarning: {
        color: themeColors.primary,
        fontSize: 12,
        lineHeight: 16,
        fontFamily: "Point-SemiBold",
    },
    addButton: {
        minHeight: 54,
        borderRadius: 12,
        backgroundColor: themeColors.primary,
        paddingHorizontal: 16,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    addButtonDisabled: {
        opacity: 0.72,
    },
    addButtonText: {
        color: themeColors.textOnPrimary,
        fontSize: 16,
        fontFamily: "Point-SemiBold",
    },
    addButtonTextDisabled: {
        color: themeColors.textSecondary,
    },
    addButtonIcon: {
        width: 30,
        height: 30,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: themeColors.notification,
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    addButtonIconDisabled: {
        borderColor: themeColors.border,
    },
    limitText: {
        color: themeColors.textSecondary,
        fontSize: 12,
        fontFamily: "Point-Regular",
        lineHeight: 16,
        paddingHorizontal: 4,
    },
    emptyState: {
        flex: 1,
        minHeight: 220,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 24,
        gap: 8,
    },
    emptyTitle: {
        color: themeColors.text,
        fontSize: 18,
        fontFamily: "Point-SemiBold",
        textAlign: "center",
    },
    emptyText: {
        color: themeColors.textSecondary,
        fontSize: 14,
        fontFamily: "Point-Regular",
        textAlign: "center",
        lineHeight: 20,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.55)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 24,
    },
    modalCard: {
        width: "100%",
        maxWidth: 360,
        borderRadius: 20,
        backgroundColor: themeColors.card,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
        padding: 20,
        gap: 10,
        ...SHADOW,
    },
    modalTitle: {
        color: themeColors.text,
        fontSize: 18,
        fontFamily: "Point-Bold",
    },
    modalAddress: {
        color: themeColors.textSecondary,
        fontSize: 15,
        fontFamily: "Point-Regular",
        lineHeight: 21,
    },
    modalActions: {
        flexDirection: "row",
        gap: 10,
        marginTop: 8,
    },
    modalCancel: {
        flex: 1,
        height: 50,
        borderRadius: 16,
        backgroundColor: themeColors.cardSecondary,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
    },
    modalCancelText: {
        color: themeColors.text,
        fontSize: 15,
        fontFamily: "Point-SemiBold",
    },
    modalDelete: {
        flex: 1,
        height: 50,
        borderRadius: 16,
        backgroundColor: themeColors.notification,
        alignItems: "center",
        justifyContent: "center",
    },
    modalDeleteText: {
        color: themeColors.text,
        fontSize: 15,
        fontFamily: "Point-Bold",
    },
    sheetContent: {
        gap: 16,
        paddingBottom: 4,
    },
    dayTabs: {
        flexDirection: "row",
        gap: 8,
    },
    dayTab: {
        flex: 1,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: themeColors.border,
        backgroundColor: themeColors.background,
        paddingHorizontal: 8,
        paddingVertical: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    dayTabActive: {
        borderColor: themeColors.primary,
        backgroundColor: themeColors.card,
    },
    dayTabDisabled: {
        opacity: 0.45,
    },
    dayTabText: {
        color: themeColors.textSecondary,
        fontSize: 12,
        fontFamily: "Point-SemiBold",
        textAlign: "center",
    },
    dayTabTextActive: {
        color: themeColors.text,
    },
    dayTabTextDisabled: {
        color: themeColors.textSecondary,
    },
    slotList: {
        gap: 8,
    },
    slotRow: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: themeColors.cardBorder,
        backgroundColor: themeColors.card,
        paddingHorizontal: 14,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    slotText: {
        flex: 1,
        color: themeColors.text,
        fontSize: 14,
        fontFamily: "Point-Regular",
    },
    sheetEmptyState: {
        minHeight: 120,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 12,
    },
    sheetEmptyText: {
        color: themeColors.textSecondary,
        fontSize: 14,
        fontFamily: "Point-Regular",
        textAlign: "center",
        lineHeight: 20,
    },
    sheetSaveButton: {
        minHeight: 52,
        borderRadius: 14,
        backgroundColor: themeColors.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    sheetSaveButtonText: {
        color: themeColors.textOnPrimary,
        fontSize: 16,
        fontFamily: "Point-Bold",
    },
});

export default styles;
